### ISSUE TITLE
Maximum number of entries into the forwarding table

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/macFd#2]
Exceeding IEEE 802.1Q-2018, which is describing
- the maximum number of entries supported by the hardware (Capability attribute)

the modelling shall also support 
- a configurable maximum number of entries into the forwarding table (Configuration attribute)
- and a threshold cross alarm definition expressed in percent of the configurable maximum number of entries (Configuration attribute).

**Comment by demx8as6** [comment]
Proposal to "reject" the request after the group has decided (add references) that no mac-fcs are modeled. 
Note: feature for max VLAN-FC does already exist. 
TODO: @demx8as6 create proposal to reject and to be approved on Oct 5th.

**Comment by openBackhaul** [comment]
**Following changes have been added:**
- Existing MacFdCapability::maximumNumberOfEntries : Integer [1] = -1 attribute has been renamed to supportedMaximumNumberOfEntries
- New MacFdConfiguration::maximumNumberOfEntries : Integer [1] = -1 attribute has been added with comment: "Number of entries in the forwarding table shall be limited to this value."

**Comment by openBackhaul** [comment]
Fixed with MacFd_1.0.0-tsp.220328.1700
