### ISSUE TITLE
Technology specific amendment to the ForwardingDomain class for documenting current forwarding according to IEEE 802.1 .

### ISSUE THREAD

**Issue by demx8as6** [openBackhaul/macFd#5]
Providing learned MAC Adresses from the bridging Table per VLAN.
 
The Following Attribute in needed in MacFdStatus 
MAC_address_connected           Device   Hexadecimal with capital letter and seperated with “-“                The MAC Address from the ARP/briging  table      58-AC-7B-9B-0C-T5 
 
It should be possible to filter the macFD by VLAN
e.g.
vlan       Device   INTEGER             The virtual LAN ID            430
 
Usage for information:
To analyze the VLAN topology, the plan is to use the ARP tables of the devices
By nature, the algorithm does not always have a single solution, as ARP does show the exit port, but not the neighbor which brings the learned MAC address into account. 
In order to ensure the exactitude of the MAC extraction, an illustration for each type of MW equipment will be cited in the specification document. The extraction protocol will be defined by the entity responsible of the solution delivery  
 
![image](https://user-images.githubusercontent.com/9154981/123801935-0784f400-d8eb-11eb-8fe3-0b98c118b028.png)

**Comment by demx8as6** [comment]
**Idea commonly elaborated during Modeling call on Tuesday, 7th of September 2021:**

RPC get-learned-mac-addresses
- input (not used for this RPC)
- output
-- list learned-mac-addresses
--- leaf mac-fd-reference (type leafref) 
--- leaf mac-address
--- leaf vlan-id uint (type as used in VLAN-FC)
--- leaf ltp-reference - type leafref -> from her the app knows the MAC-FD and the physical port

**Comment by openBackhaul** [comment]
**Proposal to be decided on the 5G-xhaul call on 29th of September 2021:**
Completing the MacFd modelling by the following changes:
- Adding MacFdOperations interface with "Group of operations, which are effective on the MAC switch." comment
- Adding MacFdOperations::provideLearnedMacAddresses operation with with macTableEntryList output attribute of MacTableEntryType datatype and [*] multiplicity and "List of MAC address table entries." comment
- Adding MacTableEntryType datatype holding the following 4 read-only attributes that do not initiate AttributeValueChangeNotfications:
  - _affectedMacFd attribute for referencing an existing ForwardingDomain and "Reference to the MAC switch, which is holding the MAC address table that is containing this entry." comment
  - macAddress attribute of MacAddress datatype (from existing IETF address types) with 00:00:00:00:00:00 default value and "MAC address that can be reached on the referenced interface." comment
  - vlanId attribute of Int64 datatype with -1 default value and "VLAN, in which the MAC address can be reached at the referenced interface. If VLAN bridging would be deactivated, this value should be 0." comment
  - _egressLtp attribute for referencing an existing LTP and "MAC interface that connects the MAC address." comment

**Comment by demx8as6** [comment]
**Decision on the 5G-xhaul call on 29th of September 2021:**
Completing the MacFd modelling by the following changes:
- Adding MacFdOperations interface with "Group of operations, which are effective on the MAC switch." comment
- Adding MacFdOperations::provideLearnedMacAddresses operation with with macTableEntryList output attribute of MacTableEntryType datatype and [*] multiplicity and "List of MAC address table entries." comment
- Adding MacTableEntryType datatype holding the following 4 read-only attributes that do not initiate AttributeValueChangeNotfications:
  - _affectedMacFd attribute for referencing an existing ForwardingDomain and "Reference to the MAC switch, which is holding the MAC address table that is containing this entry." comment
  - macAddress attribute of MacAddress datatype (from existing IETF address types) with 00:00:00:00:00:00 default value and "MAC address that can be reached on the referenced interface." comment
  - vlanId attribute of Int64 datatype with -1 default value and "VLAN, in which the MAC address can be reached at the referenced interface. If VLAN bridging would be deactivated, this value should be 0." comment
  - _egressLtp attribute for referencing an existing LTP and "MAC interface that connects the MAC address." comment

**Comment by openBackhaul** [comment]
Fixed with MacFd_1.0.0-tsp.220328.1700
